### ISSUE TITLE
could we / should we change the footer?

### ISSUE THREAD

**Issue by andybrwr** [ScratchAT/scratchNavBar#1]
we could link to stuffs idk

**Comment by pen-and-paper** [comment]
eh, is there really a need to change it? I'm assuming this is about Discuss being removed (#bring_it_back) so I don't really think it needs to be changed....

then again linking to the ATs would be convenient ;)

**Comment by andybrwr** [comment]
ATS/secret forum

**Comment by pen-and-paper** [comment]
yeah

**Comment by VutonDesign** [comment]
Seems a good idea.
